name: eye2025
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  photo_view: ^0.15.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Edmund
      fonts:
        - asset: assets/fonts/Edmund-Free.ttf
